import type { LabPageKey } from '../shared.js';
import type {
  LabPerformanceAnalysis,
  LabPrimitiveStructure,
  LabPrimitiveStructureLayer,
} from './types.js';

function primitiveStructure(
  title: string,
  summary: string,
  layers: readonly LabPrimitiveStructureLayer[],
): LabPrimitiveStructure {
  return {
    title,
    summary,
    layers,
  };
}

export const LAB_PERFORMANCE_ANALYSIS: Record<
  LabPageKey,
  LabPerformanceAnalysis
> = {
  plane: {
    label: 'ColorPlane',
    primitiveStructure: primitiveStructure(
      'ColorPlane primitive',
      'A bounded interactive plane composed from a base surface, gamut raster, overlay helpers, and an input thumb anchored above the render layer.',
      [
        {
          id: 'plane-frame',
          label: 'Frame',
          detail: 'Rounded pointer target that clips the color field.',
          color: '#1f2937',
          width: 4.8,
          height: 3.4,
          depth: 0.22,
          offsetZ: -0.24,
          opacity: 0.88,
        },
        {
          id: 'gamut-raster',
          label: 'Gamut raster',
          detail: 'Canvas/WebGL color field for the selected axes.',
          color: '#ef4444',
          width: 4.38,
          height: 2.88,
          depth: 0.08,
          offsetZ: 0.02,
          opacity: 0.9,
        },
        {
          id: 'overlay-boundaries',
          label: 'Overlay paths',
          detail: 'Optional sRGB/P3 boundaries and helper points.',
          color: '#22d3ee',
          width: 3.74,
          height: 2.34,
          depth: 0.06,
          offsetX: -0.08,
          offsetY: 0.1,
          offsetZ: 0.32,
          opacity: 0.68,
        },
        {
          id: 'active-thumb',
          label: 'Thumb',
          detail: 'Keyboard and pointer handle that commits color changes.',
          color: '#f8fafc',
          width: 0.54,
          height: 0.54,
          depth: 0.2,
          offsetX: -1.06,
          offsetY: 0.82,
          offsetZ: 0.72,
          opacity: 0.96,
        },
      ],
    ),
  },
  input: {
    label: 'Input Primitive',
    primitiveStructure: primitiveStructure(
      'PrimitiveValueInput',
      'A compact field shell with a value cell, focus ring, and optional scrub handle arranged on one horizontal control plane.',
      [
        {
          id: 'input-shell',
          label: 'Shell',
          detail: 'Stable rounded field surface and hit area.',
          color: '#334155',
          width: 4.4,
          height: 1.22,
          depth: 0.22,
          offsetZ: -0.2,
          opacity: 0.9,
        },
        {
          id: 'value-cell',
          label: 'Value cell',
          detail: 'Editable text/input region with numeric parsing.',
          color: '#64748b',
          width: 3.24,
          height: 0.72,
          depth: 0.12,
          offsetX: 0.34,
          offsetZ: 0.08,
          opacity: 0.88,
        },
        {
          id: 'scrub-handle',
          label: 'Scrub handle',
          detail: 'Optional drag affordance for coarse/fine stepping.',
          color: '#38bdf8',
          width: 0.58,
          height: 0.72,
          depth: 0.18,
          offsetX: -1.78,
          offsetZ: 0.34,
          opacity: 0.94,
        },
      ],
    ),
  },
  inputMulti: {
    label: 'Input Multi',
    primitiveStructure: primitiveStructure(
      'MultiInputControl',
      'A segmented value editor made from repeated primitive inputs inside a shared channel group.',
      [
        {
          id: 'group-shell',
          label: 'Group shell',
          detail: 'Shared rounded container for channel fields.',
          color: '#1e293b',
          width: 5.2,
          height: 1.18,
          depth: 0.2,
          offsetZ: -0.2,
          opacity: 0.9,
        },
        {
          id: 'channel-one',
          label: 'Channel field',
          detail: 'First repeated primitive input segment.',
          color: '#0f766e',
          width: 1.12,
          height: 0.76,
          depth: 0.12,
          offsetX: -1.68,
          offsetZ: 0.1,
          opacity: 0.9,
        },
        {
          id: 'channel-two',
          label: 'Channel field',
          detail: 'Middle repeated primitive input segment.',
          color: '#0ea5e9',
          width: 1.12,
          height: 0.76,
          depth: 0.12,
          offsetX: -0.42,
          offsetZ: 0.18,
          opacity: 0.9,
        },
        {
          id: 'channel-three',
          label: 'Channel field',
          detail: 'Trailing repeated primitive input segment.',
          color: '#8b5cf6',
          width: 1.12,
          height: 0.76,
          depth: 0.12,
          offsetX: 0.84,
          offsetZ: 0.26,
          opacity: 0.9,
        },
        {
          id: 'alpha-channel',
          label: 'Alpha channel',
          detail: 'Optional alpha segment with the same primitive contract.',
          color: '#f59e0b',
          width: 0.82,
          height: 0.76,
          depth: 0.12,
          offsetX: 1.94,
          offsetZ: 0.34,
          opacity: 0.9,
        },
      ],
    ),
  },
  checkbox: {
    label: 'Checkbox',
    primitiveStructure: primitiveStructure(
      'Checkbox primitive',
      'A row target with an independent indicator box, check glyph layer, and label surface.',
      [
        {
          id: 'row-target',
          label: 'Row target',
          detail: 'Full click and focus target for the checkbox row.',
          color: '#334155',
          width: 4.6,
          height: 1.12,
          depth: 0.18,
          offsetZ: -0.18,
          opacity: 0.88,
        },
        {
          id: 'indicator-box',
          label: 'Indicator',
          detail: 'Visual checkbox box and state surface.',
          color: '#22c55e',
          width: 0.68,
          height: 0.68,
          depth: 0.2,
          offsetX: -1.78,
          offsetZ: 0.18,
          opacity: 0.92,
        },
        {
          id: 'check-mark',
          label: 'State glyph',
          detail: 'Pressed/checked mark drawn above the indicator.',
          color: '#f8fafc',
          width: 0.42,
          height: 0.42,
          depth: 0.08,
          offsetX: -1.78,
          offsetZ: 0.48,
          opacity: 0.96,
        },
        {
          id: 'label-copy',
          label: 'Label',
          detail: 'Text alignment layer beside the indicator.',
          color: '#64748b',
          width: 2.52,
          height: 0.38,
          depth: 0.08,
          offsetX: 0.42,
          offsetZ: 0.18,
          opacity: 0.78,
        },
      ],
    ),
  },
  slider: {
    label: 'Slider',
    primitiveStructure: primitiveStructure(
      'ColorSlider primitive',
      'A rail-driven value control with gradient track, active range, markers, and a draggable thumb on top.',
      [
        {
          id: 'slider-target',
          label: 'Target',
          detail: 'Full pointer and keyboard interaction zone.',
          color: '#1e293b',
          width: 5.2,
          height: 1.0,
          depth: 0.18,
          offsetZ: -0.2,
          opacity: 0.86,
        },
        {
          id: 'slider-rail',
          label: 'Rail',
          detail: 'Gradient track that communicates the value domain.',
          color: '#06b6d4',
          width: 4.58,
          height: 0.22,
          depth: 0.1,
          offsetZ: 0.12,
          opacity: 0.92,
        },
        {
          id: 'slider-range',
          label: 'Active range',
          detail: 'Selected value span clipped to the current rail.',
          color: '#f97316',
          width: 2.64,
          height: 0.3,
          depth: 0.1,
          offsetX: -0.58,
          offsetZ: 0.34,
          opacity: 0.88,
        },
        {
          id: 'slider-thumb',
          label: 'Thumb',
          detail: 'Draggable value handle over the rail.',
          color: '#f8fafc',
          width: 0.48,
          height: 0.76,
          depth: 0.22,
          offsetX: 0.78,
          offsetZ: 0.66,
          opacity: 0.96,
        },
      ],
    ),
  },
  tooltip: {
    label: 'Tooltip',
    primitiveStructure: primitiveStructure(
      'Tooltip primitive',
      'A trigger element paired with a floating content layer, arrow, and collision-aware placement plane.',
      [
        {
          id: 'trigger',
          label: 'Trigger',
          detail: 'Focusable control that owns tooltip intent.',
          color: '#475569',
          width: 2.1,
          height: 1.0,
          depth: 0.2,
          offsetY: -0.72,
          offsetZ: -0.1,
          opacity: 0.9,
        },
        {
          id: 'positioner',
          label: 'Positioner',
          detail: 'Floating layer used for side/align collision math.',
          color: '#14b8a6',
          width: 3.28,
          height: 1.0,
          depth: 0.12,
          offsetY: 0.68,
          offsetZ: 0.24,
          opacity: 0.82,
        },
        {
          id: 'content',
          label: 'Content',
          detail: 'Tooltip panel above the trigger.',
          color: '#f59e0b',
          width: 2.86,
          height: 0.72,
          depth: 0.18,
          offsetY: 0.68,
          offsetZ: 0.5,
          opacity: 0.94,
        },
        {
          id: 'arrow',
          label: 'Arrow',
          detail: 'Directional connector between content and trigger.',
          color: '#fef3c7',
          width: 0.38,
          height: 0.38,
          depth: 0.1,
          offsetY: 0.12,
          offsetZ: 0.72,
          opacity: 0.94,
        },
      ],
    ),
  },
  menu: {
    label: 'Menu',
    primitiveStructure: primitiveStructure(
      'Menu primitive',
      'A trigger connected to a floating menu surface with grouped item rows and optional nested submenu layers.',
      [
        {
          id: 'menu-trigger',
          label: 'Trigger',
          detail: 'Button that opens the floating menu layer.',
          color: '#475569',
          width: 2.28,
          height: 0.86,
          depth: 0.18,
          offsetX: -1.36,
          offsetY: -0.62,
          offsetZ: -0.12,
          opacity: 0.9,
        },
        {
          id: 'menu-content',
          label: 'Menu content',
          detail: 'Portal-mounted menu surface.',
          color: '#0f766e',
          width: 3.1,
          height: 2.58,
          depth: 0.16,
          offsetX: 0.84,
          offsetY: 0.34,
          offsetZ: 0.22,
          opacity: 0.88,
        },
        {
          id: 'menu-items',
          label: 'Item rows',
          detail: 'Repeated command rows inside the content surface.',
          color: '#38bdf8',
          width: 2.62,
          height: 1.82,
          depth: 0.1,
          offsetX: 0.84,
          offsetY: 0.34,
          offsetZ: 0.52,
          opacity: 0.82,
        },
        {
          id: 'submenu-layer',
          label: 'Submenu',
          detail: 'Optional nested flyout aligned from an item row.',
          color: '#a78bfa',
          width: 1.52,
          height: 1.72,
          depth: 0.12,
          offsetX: 2.56,
          offsetY: 0.48,
          offsetZ: 0.84,
          opacity: 0.74,
        },
      ],
    ),
  },
  select: {
    label: 'Select',
    primitiveStructure: primitiveStructure(
      'Select primitive',
      'A closed trigger surface and floating option list with active item, icon, and value text layers.',
      [
        {
          id: 'select-trigger',
          label: 'Trigger',
          detail: 'Compact button that displays the selected value.',
          color: '#334155',
          width: 3.52,
          height: 0.92,
          depth: 0.2,
          offsetY: -0.68,
          offsetZ: -0.12,
          opacity: 0.9,
        },
        {
          id: 'select-value',
          label: 'Value text',
          detail: 'Selected label and optional icon in the trigger.',
          color: '#38bdf8',
          width: 2.36,
          height: 0.36,
          depth: 0.08,
          offsetX: -0.28,
          offsetY: -0.68,
          offsetZ: 0.2,
          opacity: 0.86,
        },
        {
          id: 'select-content',
          label: 'Option list',
          detail: 'Floating menu/listbox surface.',
          color: '#0f766e',
          width: 3.72,
          height: 2.34,
          depth: 0.16,
          offsetY: 0.72,
          offsetZ: 0.32,
          opacity: 0.86,
        },
        {
          id: 'active-option',
          label: 'Active option',
          detail: 'Focused or selected option row.',
          color: '#f59e0b',
          width: 3.24,
          height: 0.48,
          depth: 0.08,
          offsetY: 0.4,
          offsetZ: 0.62,
          opacity: 0.9,
        },
      ],
    ),
  },
  toggleButton: {
    label: 'Toggle Button',
    primitiveStructure: primitiveStructure(
      'ToggleButton primitive',
      'A single pressable state container with icon/text content and layered selection feedback.',
      [
        {
          id: 'toggle-hit-area',
          label: 'Hit area',
          detail: 'Button target and focus boundary.',
          color: '#1e293b',
          width: 3.2,
          height: 1.04,
          depth: 0.2,
          offsetZ: -0.14,
          opacity: 0.9,
        },
        {
          id: 'state-fill',
          label: 'State fill',
          detail: 'On/off visual fill layer.',
          color: '#3b82f6',
          width: 2.82,
          height: 0.7,
          depth: 0.1,
          offsetZ: 0.16,
          opacity: 0.76,
        },
        {
          id: 'content-layer',
          label: 'Content',
          detail: 'Icon and label composition.',
          color: '#f8fafc',
          width: 1.74,
          height: 0.32,
          depth: 0.08,
          offsetZ: 0.48,
          opacity: 0.94,
        },
      ],
    ),
  },
  toggle: {
    label: 'Toggle Group',
    primitiveStructure: primitiveStructure(
      'ToggleGroup primitive',
      'A roving group surface containing repeated toggle buttons and one shared selection model.',
      [
        {
          id: 'toggle-group-shell',
          label: 'Group shell',
          detail: 'Shared segmented-control container.',
          color: '#1e293b',
          width: 4.7,
          height: 1.1,
          depth: 0.18,
          offsetZ: -0.18,
          opacity: 0.9,
        },
        {
          id: 'toggle-item-one',
          label: 'Toggle item',
          detail: 'First repeated button primitive.',
          color: '#3b82f6',
          width: 1.28,
          height: 0.72,
          depth: 0.12,
          offsetX: -1.38,
          offsetZ: 0.12,
          opacity: 0.86,
        },
        {
          id: 'toggle-item-two',
          label: 'Selected item',
          detail: 'Pressed item layer and active state.',
          color: '#22c55e',
          width: 1.28,
          height: 0.72,
          depth: 0.16,
          offsetZ: 0.32,
          opacity: 0.92,
        },
        {
          id: 'toggle-item-three',
          label: 'Toggle item',
          detail: 'Trailing repeated button primitive.',
          color: '#a78bfa',
          width: 1.28,
          height: 0.72,
          depth: 0.12,
          offsetX: 1.38,
          offsetZ: 0.12,
          opacity: 0.86,
        },
      ],
    ),
  },
};

export const LAB_PAGE_RESOURCE_HINTS: Record<LabPageKey, readonly string[]> = {
  plane: ['color-plane'],
  input: ['pages/input', 'input-'],
  inputMulti: ['input-multi'],
  checkbox: ['checkbox'],
  slider: ['slider'],
  tooltip: ['tooltip'],
  menu: ['menu'],
  select: ['select'],
  toggleButton: ['toggle-button'],
  toggle: ['toggle-group'],
};
